#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
version: "3"

services:
  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  # ---------------------
  # Database
  # ---------------------
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: hawkbit
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  # ---------------------
  # HawkBit service
  # ---------------------
  hawkbit:
    build:
      context: ./0.3.0M6-mysql
    image: "mdrglobalcr.azurecr.io/hawkbit-update-server:0.3.0M6-mysql"
    environment:
      # Configure admin user
      - "LOGIN_USERNAME=admin"
      - "LOGIN_PASSWORD=admin"
      # Configure postgresql
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_NAME=hawkbit"
      - "DB_USER=admin"
      - "DB_PASS=admin"
      # Configure message broker
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "SPRING_RABBITMQ_USERNAME=guest"
      - "SPRING_RABBITMQ_PASSWORD=guest"
      # Configure Azure BLOB storage
      - "AZURE_BLOB_CONN_STRING=DefaultEndpointsProtocol=https;AccountName=mdrtoolsglobalhawkbit;AccountKey=HUJKr+BM72X6q2eMTiBjm3nup3WQOAhzWTCm4uQnYqgX4H9CZC1Y83qIpB+t57R7xvTIbVJZROHWCocMXqAY+w==;EndpointSuffix=core.windows.net"
      - "AZURE_BLOB_CONTAINER_NAME=hawkbit"
    restart: always
    ports:
      - "8080:8080"
    labels:
      NAME: "hawkbit"

volumes:
  data:
